publish: true
siteTitle: drFrederson
pagetitle: Directory wide title 
baseurl: 
jsdelivrdomain: //cdn.jsdelivr.net/
template: plain
prefillpath: source/drf/example.md
cssjsversion: 1
description: Some general site  wide description
