publish: true
siteTitle: drFrederson
pagetitle: Directory wide title 
baseurl: 
jsdelivrdomain: //cdn.jsdelivr.net/
template: plain
cssjsversion: 1
comment: false
webedit: true
description: Some general site  wide description
