htmlextension: .html
tplextension: .html
namespaceseparator: ":"
metaseparator: "\n#meta#"
defaulttemplate: plain
directory:
    template: ../template/
    source: ../source/
    area: ../source/area/
    html: ../html/
