htmlextension: .html
tplextension: .html
namespaceseparator: ":"
metaseparator: "\n#meta#"
defaulttemplate: plain
sourceexclude: '.git'
directory:
    template: ../template/
    source: ../source/
    area: ../source/area/
    html: ../html/
    json: ../json/
