htmlextension: .html
tplextension: .html
sourceextension: .md
webwrite: true
namespaceseparator: ":"
metaseparator: "\n#meta#"
defaulttemplate: plain
sourceexclude: '.git'
dateformat: 'Y-m-d H:i'
gitsource: false
directory:
    template: template
    source: source
    area: source/area
    html: html
    json: json
